<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function floating_action_buttons_form_node_form_alter(array &$form, FormStateInterface $form_state) {
  $systemTheme = \Drupal::config('system.theme');
  $admin = $systemTheme->get('admin');
  $default = $systemTheme->get('default');
  $theme = \Drupal::theme()->getActiveTheme()->getName();
  if ($theme === $admin || $theme === $default) {
    $form['#attached']['library'][] = 'floating_action_buttons/floating_action_buttons.admin';
  }
}
